sudo: false

language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27

install:
  - git clone https://github.com/eclipse/paho.mqtt.testing.git || true
  - pip install tox

script:
  - tox
